defaultProject: data-product-framework
defaultLocation: us-central1
defaultDataset: slv_sales
defaultAssertionDataset: dpf_assertions
dataformCoreVersion: 3.0.0

vars:
  raw_dataset: raw_ora_local
  stg_dataset: stg_sales
  slv_dataset: slv_sales
  gold_dataset: gold_sales
  restatement_window_days: "90"
