# dpf: element=policy:PT-1 satisfies=R-12
resource "google_data_catalog_taxonomy" "product" {
  project                = var.project_id
  region                 = var.region
  display_name           = "sales_performance"
  description            = "Column policy tags for sales_performance (generated by dpf)."
  activated_policy_types = ["FINE_GRAINED_ACCESS_CONTROL"]
}

# dpf: element=policy:PT-1 satisfies=R-12
resource "google_data_catalog_policy_tag" "pii_contact" {
  taxonomy     = google_data_catalog_taxonomy.product.id
  display_name = "pii_contact"
  description  = "dim_customer: customer_email, customer_phone (PT-1)"
}

# dpf: element=policy:PT-1 satisfies=R-12
resource "google_data_catalog_policy_tag_iam_member" "pii_contact_reader_contact_reader_group" {
  policy_tag = google_data_catalog_policy_tag.pii_contact.name
  role       = "roles/datacatalog.categoryFineGrainedReader"
  member     = "group:${var.contact_reader_group}"
}

# dpf: element=policy:PT-1 satisfies=R-12
resource "google_bigquery_datapolicy_data_policy" "pt_1" {
  project          = var.project_id
  location         = var.region
  data_policy_id   = "sales_performance_pt_1"
  policy_tag       = google_data_catalog_policy_tag.pii_contact.name
  data_policy_type = "DATA_MASKING_POLICY"
  data_masking_policy {
    predefined_expression = "ALWAYS_NULL"
  }
}

# dpf: element=policy:PT-1 satisfies=R-12
resource "google_bigquery_datapolicy_data_policy_iam_member" "pt_1_masked_analyst_group" {
  project        = var.project_id
  location       = var.region
  data_policy_id = google_bigquery_datapolicy_data_policy.pt_1.data_policy_id
  role           = "roles/bigquerydatapolicy.maskedReader"
  member         = "group:${var.analyst_group}"
}
