# dpf: element=observability:quality_scans,model:fct_order_line implements=enforce-data-quality
resource "google_dataplex_datascan" "dq_fct_order_line" {
  project      = var.project_id
  location     = var.region
  data_scan_id = "dpf-sales-performance-fct-order-line"
  display_name = "dpf sales_performance fct_order_line"
  description  = "Knowledge Catalog data quality scan of fct_order_line: grain, keys and quality rules (generated by dpf)."
  data {
    resource = "//bigquery.googleapis.com/projects/${var.project_id}/datasets/slv_sales/tables/fct_order_line"
  }
  execution_spec {
    trigger {
      schedule {
        cron = "CRON_TZ=Australia/Perth 30 6 * * *"
      }
    }
  }
  data_quality_spec {
    sampling_percent = 100
    rules {
      name      = "order-id-not-null"
      dimension = "COMPLETENESS"
      column    = "order_id"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "order-line-no-not-null"
      dimension = "COMPLETENESS"
      column    = "order_line_no"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "grain-unique"
      dimension = "UNIQUENESS"
      sql_assertion {
        sql_statement = "SELECT order_id, order_line_no FROM $${data()} GROUP BY order_id, order_line_no HAVING COUNT(*) > 1"
      }
    }
    rules {
      name      = "customer-id-not-null"
      dimension = "COMPLETENESS"
      column    = "customer_id"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "product-id-not-null"
      dimension = "COMPLETENESS"
      column    = "product_id"
      threshold = 1
      non_null_expectation {}
    }
  }
}

# dpf: element=observability:quality_scans,model:sales_performance_monthly implements=enforce-data-quality
resource "google_dataplex_datascan" "dq_sales_performance_monthly" {
  project      = var.project_id
  location     = var.region
  data_scan_id = "dpf-sales-performance-sales-performance-monthly"
  display_name = "dpf sales_performance sales_performance_monthly"
  description  = "Knowledge Catalog data quality scan of sales_performance_monthly: grain, keys and quality rules (generated by dpf)."
  data {
    resource = "//bigquery.googleapis.com/projects/${var.project_id}/datasets/gold_sales/tables/sales_performance_monthly"
  }
  execution_spec {
    trigger {
      schedule {
        cron = "CRON_TZ=Australia/Perth 30 6 * * *"
      }
    }
  }
  data_quality_spec {
    sampling_percent = 100
    rules {
      name      = "year-month-not-null"
      dimension = "COMPLETENESS"
      column    = "year_month"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "customer-segment-not-null"
      dimension = "COMPLETENESS"
      column    = "customer_segment"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "product-category-not-null"
      dimension = "COMPLETENESS"
      column    = "product_category"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "region-not-null"
      dimension = "COMPLETENESS"
      column    = "region"
      threshold = 1
      non_null_expectation {}
    }
    rules {
      name      = "grain-unique"
      dimension = "UNIQUENESS"
      sql_assertion {
        sql_statement = "SELECT year_month, customer_segment, product_category, region FROM $${data()} GROUP BY year_month, customer_segment, product_category, region HAVING COUNT(*) > 1"
      }
    }
  }
}
