# dpf: element=port:sales_performance_partner_extract satisfies=R-13
resource "google_bigquery_analytics_hub_data_exchange" "sales_partner_exchange" {
  project          = var.project_id
  location         = var.region
  data_exchange_id = "sales_partner_exchange"
  display_name     = "sales_partner_exchange"
  description      = "sales_performance: external sharing exchange (generated by dpf)."
}

# dpf: element=port:sales_performance_partner_extract satisfies=R-13
resource "google_bigquery_analytics_hub_listing" "sales_performance_monthly_extract" {
  project          = var.project_id
  location         = var.region
  data_exchange_id = google_bigquery_analytics_hub_data_exchange.sales_partner_exchange.data_exchange_id
  listing_id       = "sales_performance_monthly_extract"
  display_name     = "sales_performance_partner_extract"
  description      = "sales_performance_partner_extract: one row per closed month per product category per region."
  bigquery_dataset {
    dataset = google_bigquery_dataset.share.id
  }
  restricted_export_config {
    enabled               = true
    restrict_query_result = true
  }
}

# dpf: element=port:sales_performance_partner_extract satisfies=R-13
resource "google_bigquery_analytics_hub_listing_iam_member" "sales_performance_monthly_extract_subscriber" {
  count            = var.partner_subscriber == "" ? 0 : 1
  project          = var.project_id
  location         = var.region
  data_exchange_id = google_bigquery_analytics_hub_data_exchange.sales_partner_exchange.data_exchange_id
  listing_id       = google_bigquery_analytics_hub_listing.sales_performance_monthly_extract.listing_id
  role             = "roles/analyticshub.subscriber"
  member           = var.partner_subscriber
}
